version: "3.0"
services:

  postgres:
    image: "postgres:13-alpine"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    restart: always
    environment:
      - POSTGRES_USER=openendio
      - POSTGRES_PASSWORD=openendio
      - POSTGRES_DB=openend
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - soppy
    hostname: postgres
    ports:
      - "15444:5432"

volumes:
  postgres:

networks:
  soppy:
    driver: bridge
